william_web_server/models.py
from william_web_server import db, login_manager
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask_login import UserMixin
from datetime import datetime
from flask import current_app


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)

    def get_reset_token(self, expires_sec=600):
        s = Serializer(current_app.config['SECRET_KEY'], expires_sec)
        return s.dumps({'user_id': self.id}).decode('utf-8')

    @staticmethod
    def verify_reset_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            user_id = s.loads(token)['user_id']
        except:
            return None
        return User.query.get(user_id)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}')"


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"

william_web_server/__init__.py
# -*- coding: utf-8 -*-
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from william_web_server.config import Config

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_message_category = 'info'
login_manager.login_message = u"欢迎使用高效写作素材库，注册后即可免费试用大部分功能。"
login_manager.login_view = 'users.login'

mail = Mail()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # from william_web_server.users.routes import users
    # from william_web_server.posts.routes import posts
    from william_web_server.main.routes import main
    # from william_web_server.errors.handlers import errors

    # app.register_blueprint(users)
    # app.register_blueprint(posts)
    app.register_blueprint(main)
    # app.register_blueprint(errors)

    return app

# 关于加密补充：1）明文储存——————不需要破解 2）对称加密——————破解难度中等（但是前提是key必须要保密）3）HASH (单项、特殊（salt）)
# 1）saltRounds:正数
# 2）myPassword:明文密码字符串
# 3）salt:128bit, 22字符
# 4）myHash：循环加salt进行hash得到的结果

william_web_server/main/routes.py
from flask import Blueprint, request, render_template
from william_web_server.models import Post

main = Blueprint('main', __name__)


@main.route('/')
def index():
    print('index')
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=3)
    return render_template("main.html", posts=posts)


@main.route('/about')
def about():
    return render_template("about.html", title="关于语料库藏")

templates/about.html
{% extends "general_layout.html" %}
{% block content %}
    <h1>关于我们：这是写书人的语料库关于我们的页面</h1>
{% endblock content %}

templates/general_layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='main.css')}}">

    {% if title %}
        <title>乐学偶得官网 - {{ title }}</title>
    {% else %}
        <title>乐学偶得官网</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                <a class="navbar-brand mr-4" href="/">乐学知识，偶得美好</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.index') }}">主页</a>
                    <a class="nav-item nav-link" href="{{ url_for('main.about') }}">关于</a>
                    </div>
                    <!-- 右侧Nav Bar -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" href=" {{ url_for('users.account') }}">个人主页</a>
                            <a class="nav-item nav-link" href=" {{ url_for('posts.new_post') }}">写文章</a>
                            <a class="nav-item nav-link" href=" {{ url_for('users.logout') }}">登出</a>
                        {% else %}
                            <a class="nav-item nav-link" href=" {{ url_for('users.login') }}">登录</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">注册</a>
                        {% endif %}
                    </div>
                </div>
                </div>
            </nav>
            </header>
        
        
            <main role="main" class="container">
            <div class="row">
                <div class="col-md-8">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category , message in messages %}
                                <div class= "alert alert-{{ category }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}
                </div>
                <div class="col-md-4">
                <div class="content-section">
                    <h3>导航栏</h3>
                    <p class='text-muted'>这里可以写你想要的内容
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light">最新文章</li>
                        <li class="list-group-item list-group-item-light">公告</li>
                        <li class="list-group-item list-group-item-light">日历</li>
                        <li class="list-group-item list-group-item-light">其他</li>
                    </ul>
                    </p>
                </div>
                </div>
            </div>
            </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/main.html
{% extends "general_layout.html" %}
{% block content %}
    {% for post in posts.items %}
      <article class="media content-section">
        <img class="rounded-circle article-img " src="{{ url_for('static', filename='user_profile_pics/' + post.author.image_file)}}" >
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d')}}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post',post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
      </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1,right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-10" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-10" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}

{% endblock content %}